version: "3.8"

services:
  odyssey:
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
      - cache
    networks:
      - odyssey
    # command: go run cmd/main.go -b 0.0.0.0
    command: air ./cmd/main.go -b 0.0.0.0
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    networks:
      - odyssey
    volumes:
      - postgres-db:/var/lib/postgresql/data
  cache:
    image: redis:6.2-alpine
    restart: always
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_DB_NUMBER=${REDIS_DB_NUMBER}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass $REDIS_PASSWORD
    volumes: 
      - redis-cache:/var/lib/redis/data
    networks:
      - odyssey

volumes:
  postgres-db:
  redis-cache:

networks:
  odyssey:
